name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/**.md'
      - '.github/**'

jobs:
  publish:
    name: Publish the app
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
